### ISSUE TITLE
[bisos.iteration] Termination rule

### ISSUE THREAD

**Issue by renatoloureiro** [tcunis/bisosprob#11]
From a few tests, it's possible to notice that having the current Bilinear problem solver with a fixed number of iterations as a termination rule might not be efficient and actually a few algorithms currently in the literature require more sophisticated termination rule. Right now the current solver, stops before the N iterations only when at a certain stage the problem is defined as infeasible.
For example, the termination rule can be such that we compare gamma with the previous gamma, and if the new gamma decreases the value, the solver must stop. (this is important for the V-s iteration with varying p)

**Comment by tcunis** [comment]
I have created a new branch `termination` for this issue. There, the `init`-step checks for a convergence flag in the info-struct to determine whether or not the iteration should be terminated ([line 19](https://github.com/tcunis/bisosprob/blob/2ec5b42d9826bf9b1f6f89d2e066223f3101e233/%2Bbisos/%2Biteration/%2Bstep/init.m#L19)):

> stop = isfield(info,'converged') && info.converged;

It is important to have the iteration stopped by the `init`-step, not anywhere else, as it leads to the previous (successful) iteration being properly logged. Stopping the iteration in any other step is considered a failure (= fall back to previous successful iteration).

**Comment by renatoloureiro** [comment]
I already started implementing it and currently I didn't change anything in the `init`-step, I added a struct in the prob that contains the condition that the user intends to be evaluated at the end of each cycle.
inside prob exists the struct "termrule" which has the following properties:
> previous
> after
> operator

Essentially whenever the cycle is at the last step (which is 'obj'), it evaluates the condition.
I will insert the condition evaluation inside the cycle [line 58](https://github.com/tcunis/bisosprob/blob/master/%2Bbisos/%40Iteration/run.m) 

I will check your approach, maybe it's cleaner than mine.

**Comment by renatoloureiro** [comment]
To add the terminal rule <img src="https://render.githubusercontent.com/render/math?math={\color{red}\gamma* > \gamma }">:
> iter = iter.addtermrule(previous, after, operator)

example:

> iter=iter.addtermrule( 'g' , 'g' , '>' )

**Comment by tcunis** [comment]
Please keep it the way I've described and set a convergence flag in whichever step you check the termination rule. If you have a user-defined termination, it would be better to create a new `step`-subclass similar to [`objective`](https://github.com/tcunis/bisosprob/blob/2ec5b42d9826bf9b1f6f89d2e066223f3101e233/+bisos/+iteration/+step/objective.m) (set `varin` to the variables need for the comparison and `varout` to empty). The auto routing can take care of it.

**Comment by tcunis** [comment]
In my experiences with the classical V-s-iteration, having small negative steps in γ or ρ (but especially γ!) isn't necessarily the end of the world. I've had iteration runs where the iteration would recover and still obtain better results afterwards. Keep in mind that the scaling of the Lyapunov is really arbitrary and mostly a question of technicalities in the convex solver.

**Comment by renatoloureiro** [comment]
> In my experiences with the classical V-s-iteration, having small negative steps in γ or ρ (but especially γ!) isn't necessarily the end of the world. I've had iteration runs where the iteration would recover and still obtain better results afterwards. Keep in mind that the scaling of the Lyapunov is really arbitrary and mostly a question of technicalities in the convex solver.

For the V-s iteration I mean the beta instead of the gamma which is associated with the level set of the shape function, because the shape function is constant over runs, so having the beta always increasing most likely means a better result, but when the opposite happens (maintains constant or decreases) most likely the solution is worse in that iteration.

**Comment by renatoloureiro** [comment]
> 
> To compute the norm of the difference in two polynomials we can make use of the norm on the vector space of polynomials, viz.
> 
> ![](https://camo.githubusercontent.com/7527ed2921279a3650e8dfbf1d960f84666c6842d5052026f835bb57fd66c0bb/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e696d6167653f5c7c2673706163653b70285c63646f74292673706163653b5c7c5e322673706163653b3d2673706163653b5c696e745f442673706163653b5c7c2673706163653b702878292673706163653b5c7c5e322673706163653b5c6f70657261746f726e616d652673706163653b642673706163653b78)
> 
> on a suitable domain D such as the unit box.

That's a rather interesting approach, I will take that into consideration.

**Comment by renatoloureiro** [comment]
This weekend I will commit a few changes that are related to the convergence step, essentially the user requests a certain level set that wants to motorize, ex.:
>  iter = iter.addconvergence({'V' 'g'});

This step is intended to check whether or not the the polynomial and it's previous has change significantly or not, in other words the norm of the difference between two polynomials is evaluated. 
A new step type was created but because this step needs past values, the state-machine needs to be specific to this one:
> % state-machine
>    if ~strcmp(step.type, 'convergence')
>        [sol,info,stop] = run(step,obj.prob,info,sol,symbols,struct,options);
>    else
>        [sol,info,stop] = run(step,obj.prob,info,sol,symbols,struct,options, solution);
>    end

With this, there is no need to change the others. 
Regarding the `termination rule`, the idea will be similar because it needs past values.
What do you think?
