### ISSUE TITLE
[bisos.iteration] User-defined step 

### ISSUE THREAD

**Issue by renatoloureiro** [tcunis/bisosprob#8]
Currently the toolbox only has a specific set of steps that can be created (e.g. "convex" and "bisection"). It would be great to give the option to the user to create his own step in the "user routing" mode. With this addition the toolbox can be expanded to more general problems.

**Comment by renatoloureiro** [comment]
For the latter purpose, a new type of variable should be created, other than decision variable or subsidiary variable. Let's call it Auxiliary Variable, let's think of it as the shape function p and we would like it to change over time depending on the solution over each iteration. Example:
> iter = iter.adduserstep{ 'p', @(a) function_handle(a), {'V'}};

Obviously this can be used not only with the Auxiliary Variable, for example in case the next step needs the previous 'V' polynomial normalized by 'g', a step to normalize can be created.

**Comment by tcunis** [comment]
Sounds good to me. Having another type of variable seems to be more elegant than having a step, as it does not infere with the routing. In that case the interface should be similar to that of adding a subsidiary variable but with the option of an initial value. 

We could use a subscriber / observer pattern to update the auxiliary if and only if the variables it depends on changes. We (the user?) might have to decide how to handle updates if the auxiliary depends on multiple variables.

**Comment by renatoloureiro** [comment]
> We could use a subscriber / observer pattern to update the auxiliary if and only if the variables it depends on changes. We (the user?) might have to decide how to handle updates if the auxiliary depends on multiple variables.

I have two scenarios which need to be handled concerning the auxiliary variable:
i) the auxiliary variable changes depending on the other variables and whenever they change, this variable changes its value too (in this case, this variable looks pretty much like a subsidiary variable)
ii) I want the variable to change but only on specific stages of the iteration, i.e. I don't want to update it whenever its dependencies changes. 

For the last one, we may need to create a step or have a very fancy way inscribed into the variable so it knows when to change its value.

**Comment by renatoloureiro** [comment]
The auxiliary variable may have a `mode`, that specifies it to the first scenario, so no step needs to be created because it will always be updated whenever its dependencies changes.
